### ISSUE TITLE
Lower resolution for slides

### ISSUE THREAD

**Issue by tibroc** [elan-ev/opencast-bigbluebutton-integration#15]
BBB is encoding slides with 4k resolution. 1080p (or possibly even 720p) would be sufficient for the video.

**Comment by lkiesow** [comment]
> BBB is encoding slides with 4k resolution

No. Slides are upscaled later. Screen share may be higher resolution.
Slides may be upscaled later though, resulting in poor quality 4k presentation videos.

**Comment by Arnei** [comment]
The merge of #7 should help with poor quality 4k presentation videos.

If the goal is to avoid processing 4k files in Opencast, you could maybe adapt the `preencode-encoding-profile` that is used by the Partial Import Operation in the `bbb-upload` Workflow to scale all files to the desired highest resolution.
