### ISSUE TITLE
persistently disable presentation workflow

### ISSUE THREAD

**Issue by hex-m** [elan-ev/opencast-bigbluebutton-integration#2]
Hi!

In the readme for the post_archive procedure it says:

> Disable the process and publish steps by calling: `sudo bbb-record --disable presentation`

This workflow will be re-enabled with every update of BBB. So this has to be added to `apply-config.sh` to be persistent.

**Comment by Arnei** [comment]
Hi,

That's a good point. Seems we missed this as we use Ansible for automatic deployment, meaning Ansible always took care of reapplying the configuration changes. I will add your suggestion to the readme.
