### ISSUE TITLE
correct assignment of a recording to a moodle course

### ISSUE THREAD

**Issue by mwuttke** [elan-ev/opencast-bigbluebutton-integration#42]
Hello,

We are testing the opencast-bigbluebutton-integration right now. But we still have problems with the assignment of the ACLs from the Moodle course, from which the BigBlueButton (BBB) recording originate.

Our setup currently in use is right now:
Moodle version: 3.10.6+
OC-Plugin (block + tool) version: both v3.11-r5
Opencast version: 10.5
BigBlueButton version: 2.4-rc5 (tested with kurento and mediasoup)
opencast-bigbluebutton-integration version: latest master branch from October 2021

We used for testing purpose the Opencast Integration with BBB plugin version 2.4.4 for moodle with a patch from Farbod. You can find this patched plugin version here: https://github.com/mwuttke/moodle-mod_bigbluebuttonbn

The BBB recordings were successfully transferred, processed and assigned to the series that belongs to the Moodle course, but the ACLs of the series are not transferred to the imported event. Unfortunately, only the ACLs given by the post_archive_config.toml file are transferred (readPerm & writePerm) and not also those of the Moodle course (e.g. courseid_Instructor & courseid_Learner). By the way, the Moodle site from which the videos are uploaded uses the LTI authentication and the moodle role provider.

Do you have any idea what's going wrong?
With regards,
Michael

**Comment by lkiesow** [comment]
By default, event ACLs will always overwrite series ACLs in Opencast. You can configure Opencast to merge these based on roles or actions, but that makes the ACL handling more complex and can be confusing for users.

The relevant configuration for this is: https://github.com/opencast/opencast/blob/f7a144a482b9ea8aff831f796c123a9353bc2bbd/etc/org.opencastproject.authorization.xacml.XACMLAuthorizationService.cfg

The alternative would be to set no ACL at all in the `post_archive` script. No episode ACL means that the series ACL takes will be used. But make sure the user used for ingests is still able to write to the event.

**Comment by mwuttke** [comment]
Ok, so simple it can be! The "alternativ" not to set ACLs for the event in the post_archive.config script solve the problem! ;-)

Thanks & Greetings,
Michael
