### ISSUE TITLE
Minimal duration for recordings that should be ingested

### ISSUE THREAD

**Issue by rrolf** [elan-ev/opencast-bigbluebutton-integration#49]
We notice that several videoconferences are recorded from the start. But several of them are not real videoconferences but simply somebody peeking into the room. 

It would be good to have a configureable minimal duration of a conference that will be ingested to Opencast (i.e. 3 Minutes).

**Comment by CGreweling** [comment]
A site notice. A lot of these recodrings which are shorter than 3Minutes. Cannot be processed by Opencast.
