### ISSUE TITLE
post_archive.rb script failing silently when there is a size 0 webcam video

### ISSUE THREAD

**Issue by manschwa** [elan-ev/opencast-bigbluebutton-integration#55]
When there is a video with the size of 0 in 
`/var/bigbluebutton/recording/raw/<meeting_ID>/video/<meeting_ID>/`
the post_archive.rb script kept failing silently.
After removing the video in question the script ran just fine.

**Comment by Arnei** [comment]
Probably fails somewhere in `checkForTranscode`.
